export { default as Template0 } from "./Template0";
export { default as Template1 } from "./Template1";
export { default as Template2 } from "./Template2";
export { default as Template3 } from "./Template3";
export { default as Template4 } from "./Template4";
export { default as Template5 } from "./Template5";
export { default as Template6 } from "./Template6";
export { default as Template7 } from "./Template7";
export { default as Template8 } from "./Template8";
