import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./context/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });
import Navbar from "./components/Design/Navbar.jsx";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <main className=" min-h-screen">
            <Navbar />
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
